---
- hosts: PTP-WEB

  tasks:

  - name: Install packages
    apt:
      pkg:
      - htop
      - apache2
      - php
      - php-mysql
      - screen
      update_cache: yes
      state: latest

  - name: Clone git repository
    git:
      repo: https://github.com/Eagle-0wl/web-for-virtualization.git
      dest: /tmp/web-for-virtualization
      clone: yes
      update: yes

  - name: Copy webpage files/configs
    copy:
      src: /tmp/web-for-virtualization/
      dest: /var/www/html
      remote_src: yes

  - name: Change directory permission
    file:
      path: /var/www/html/
      state: directory
      group: www-data
      recurse: yes
      mode: ug+rwx

  - name: Cleanup
    file:
      state: absent
      path: /tmp/push-to-production

  - name: Add IPs to /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: "{{ lookup('file', '/srv/push-to-production/created_VMs.csv') }}"
      state: present
      insertafter: EOF

  - name: Restart Apache
    ansible.builtin.systemd:
      name: apache2
      state: reloaded

  - name: Enable webserver communication with database
    shell: php -q /var/www/html/server.php  </dev/null >/dev/null 2>&1 &
